name: Windows_Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        run: npm install
      - name: Build Native
        run: npx cmake-js build --generator="Visual Studio 17 2022"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jse-binary-windows
          path: build/Release/jse_native.node